security:
  continue-on-vulnerability-error: False
  ignore-vulnerabilities:
    66040:
      expires: '2024-07-01'
      reason: VLLM has a strict dependency on outlines==0.0.34 blocking us from upgrading to 0.0.35
